version: '3'

services:
  node:
    build:
        context: .
    command: ng serve --host 0.0.0.0
    user: node:node
    volumes:
      - ./app:/home/node/app
    working_dir: /home/node/app
    ports:
      - "4200:4200"